# ConvertGPXFiles demonstrates 
# 1) extraction of GPS data stored in the standard GPX format into an 
# R data frame, using the R readGPS function; 
#
# 2) extraction of key fields (Date/Time, Latitude/Longitude, Elevation) 
# from the initial data frame into a new data frame.
#
# function arguments: 
# 
# inGPSFile (string): Input GPX file name
# outConvertFile (string): Output CSV file name
# FileType (string): Flag indicates input
# file data type: "w" for waypoints,
# "t" for tracks.
#
ConvertGPXFiles <- function(inGPSFile,outConvertFile,FileType) 
{
  # browser()
  
  if (FileType == "w")
  { 
    #
    # Read the GPX-format waypoints into a Data Frame
    # Note here: readGPS converts waypoints and tracks into 
    # data frames with different column layouts. 
    # Columns are labeled V1 - Vn)
    #
    gRawWaypt = readGPS("gpx",inGPSFile,"w")
    # 
    # Get number of observations (waypoints)
    # gRawWaypoint data frame contains the attributes that 
    # we desire in the following columns:
    #
    # V3: Observation Date (factor)
    # V4: Observation Time (factor)
    # V8: Descruptive Label (string)
    # V10: Latitude (numeric)
    # V11: Longitude (numeric)
    # V21: Elevation (Factor, includes M in last character position)
    #
    # Lets extract these columns, convert Date, Time to strings 
    # and elevation to numeric format, and construct a new data frame
    # containing only the columns of interest.
    #
    nObs = length(gRawWaypt[,"V3"])
    sDate = as.character(gRawWaypt[,"V3"])
    sTime = as.character(gRawWaypt[,"V4"])
    sLabel = as.character(gRawWaypt[,"V9"]) 
    fLat = as.numeric(gRawWaypt[,"V10"])
    fLong = as.numeric(gRawWaypt[,"V11"])
    #
    # compute the spatial bounding box for the waypoint set:
    #
    bounds = c(range(fLong),range(fLat))
    dim(bounds) = c(2,2)
    
    #
    # Elevation is a factor with the letter 'M' appended.
    # Remove this, and convert the elevation to numeric
    # This formula extracted from the HTML help file for the R readGPS package
    # 
    fAlt <- as.numeric(substring(as.character(gRawWaypt$V21),
                                 1,(nchar(as.character(gRawWaypt$V21))-1)))
    #
    # Output data frames - One 'standard' DF for file output,
    # one 'SpatialPointsDataFrame' for plotting.
    #
    dfWaypoints <<- as.data.frame(cbind(sLabel,sDate,sTime,fLat,fLong,fAlt)) 
    write.csv(dfWaypoints,outConvertFile)
    LatLongCoords = SpatialPoints(cbind(fLong,fLat),proj4string = CRS("+proj=longlat"))
    dfWayptForPlotting <<- SpatialPointsDataFrame(LatLongCoords,
                                                  bbox=as.matrix(bounds),dfWaypoints[1])
    print(sprintf("done - waypoints"))
  }
#####################   
    else if (FileType == "t")
    { 
      gRawTracks = readGPS("gpx",inGPSFile,"t")
      # 
      # A GPX file can include multiple tracks, known as track sequences, each
      # of which contains the vertices for a single track (line)
      # However, the current version of readGPS() combines all points in all 
      # track sequences into a single track. This may change in the future.
      # For this demonstration, we will convert these track points into a 
      # SpatialLinesData Frame (with a single SpatialLines object in one 'row'
      # and a single attribute - "Track_1" - attached to the track (and stored
      # in a DataFrame).
      # The data frame generated by readGPS for Tracks has a different layout:
      # 
      # V3: Latitude (numeric) 
      # V4: Longitude (numeric)
      # V14: Elevation (Factor, includes 'M' in last character position)
      # 
###############################      
      
      #
      # SpatialPointsDataFrame: one attribute (altitude) per point.
      # 
      dfTrackPoints <<- SpatialPointsDataFrame(LatLongCoords,data.frame(fAlt))
      #
      # Create SpatialLinesDF from the SpatialPointsDF.
      # First, SpatialLines object:
      #
      slTrackLine = Lines(list(Line(dfTrackPoints@coords)))
      slTrackLine@ID = "Track_One"
      SLPath = SpatialLines(list(slTrackLine),proj4string = CRS("+proj=longlat"))
      #
      # Finally, the SpatialLinesDataFrame:
      # Create a global variable using the "<<-" operator, Plot this in TheDriver().
      # 
      sldfTracksForPlotting <<- SpatialLinesDataFrame(SLPath,TrackAttributes,match.ID=FALSE)
      #
      # Write the original track points to a CSV file.
      #
      write.csv(dfTrackPoints,outConvertFile)
      print(sprintf("done - tracks")) 
    }
}
